image: node:10.17.0

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - npm install
            - npm run gulp
            - pipe: atlassian/aws-lambda-deploy:0.4.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                FUNCTION_NAME: 'dev-stage'
                COMMAND: 'update'
                ZIP_FILE: './dist/lambda.zip'
